2021-01-07T17:09:00.8906632+01:00  [INF] Get api/continent/84 called (b94943f6)
2021-01-07T17:09:16.9081518+01:00 0HM5J4Q5ECRJP:00000002 [INF] Get api/continent/84/country/14 called (1227dbe5)
2021-01-07T17:09:16.9124618+01:00 0HM5J4Q5ECRJP:00000002 [INF] Get api/continent/84/country/14 called (1227dbe5)
2021-01-07T17:09:28.4538023+01:00 0HM5J4Q5ECRJP:00000003 [INF] Get api/continent/84 called (b94943f6)
2021-01-07T17:09:28.4533000+01:00 0HM5J4Q5ECRJP:00000003 [INF] Get api/continent/84 called (b94943f6)
2021-01-07T17:09:28.4539040+01:00 0HM5J4Q5ECRJP:00000003 [INF] Get api/continent/84 called (b94943f6)
2021-01-07T17:12:03.4378423+01:00 0HM5J4Q5ECRJP:00000004 [INF] Post api/continent/ called (0def4a5a)
2021-01-07T17:12:03.4383017+01:00 0HM5J4Q5ECRJP:00000004 [INF] Post api/continent/ called (0def4a5a)
2021-01-07T17:12:03.4384718+01:00 0HM5J4Q5ECRJP:00000004 [INF] Post api/continent/ called (0def4a5a)
2021-01-07T17:12:03.4386398+01:00 0HM5J4Q5ECRJP:00000004 [INF] Post api/continent/ called (0def4a5a)
2021-01-07T17:13:42.9432168+01:00 0HM5J4Q5ECRJP:00000005 [INF] Post api/continent/ called (0def4a5a)
2021-01-07T17:13:42.9436915+01:00 0HM5J4Q5ECRJP:00000005 [INF] Post api/continent/ called (0def4a5a)
2021-01-07T17:13:42.9438217+01:00 0HM5J4Q5ECRJP:00000005 [INF] Post api/continent/ called (0def4a5a)
2021-01-07T17:13:42.9439545+01:00 0HM5J4Q5ECRJP:00000005 [INF] Post api/continent/ called (0def4a5a)
2021-01-07T17:13:42.9440831+01:00 0HM5J4Q5ECRJP:00000005 [INF] Post api/continent/ called (0def4a5a)
2021-01-07T17:14:39.8310546+01:00 0HM5J4Q5ECRJP:00000006 [INF] Post api/continent/ called (0def4a5a)
2021-01-07T17:14:39.8322707+01:00 0HM5J4Q5ECRJP:00000006 [INF] Post api/continent/ called (0def4a5a)
2021-01-07T17:14:39.8326616+01:00 0HM5J4Q5ECRJP:00000006 [INF] Post api/continent/ called (0def4a5a)
2021-01-07T17:14:39.8329623+01:00 0HM5J4Q5ECRJP:00000006 [INF] Post api/continent/ called (0def4a5a)
2021-01-07T17:14:39.8332100+01:00 0HM5J4Q5ECRJP:00000006 [INF] Post api/continent/ called (0def4a5a)
2021-01-07T17:14:39.8334976+01:00 0HM5J4Q5ECRJP:00000006 [INF] Post api/continent/ called (0def4a5a)
2021-01-07T17:14:40.3373819+01:00 0HM5J4Q5ECRJP:00000006 [ERR] An error occurred while updating the entries. See the inner exception for details. (5d65ae99)
2021-01-07T17:14:40.3375932+01:00 0HM5J4Q5ECRJP:00000006 [ERR] An error occurred while updating the entries. See the inner exception for details. (5d65ae99)
2021-01-07T17:14:40.3377243+01:00 0HM5J4Q5ECRJP:00000006 [ERR] An error occurred while updating the entries. See the inner exception for details. (5d65ae99)
2021-01-07T17:14:40.3378236+01:00 0HM5J4Q5ECRJP:00000006 [ERR] An error occurred while updating the entries. See the inner exception for details. (5d65ae99)
2021-01-07T17:14:40.3379163+01:00 0HM5J4Q5ECRJP:00000006 [ERR] An error occurred while updating the entries. See the inner exception for details. (5d65ae99)
2021-01-07T17:14:40.3379954+01:00 0HM5J4Q5ECRJP:00000006 [ERR] An error occurred while updating the entries. See the inner exception for details. (5d65ae99)
2021-01-07T17:15:11.0887076+01:00  [INF] Application is shutting down... (90f52c38)
2021-01-07T17:15:11.0886476+01:00  [INF] Application is shutting down... (90f52c38)
2021-01-07T17:15:11.0887918+01:00  [INF] Application is shutting down... (90f52c38)
2021-01-07T17:15:11.0883334+01:00  [INF] Application is shutting down... (90f52c38)
2021-01-07T17:15:11.0886750+01:00  [INF] Application is shutting down... (90f52c38)
2021-01-07T17:15:11.0887381+01:00  [INF] Application is shutting down... (90f52c38)
2021-01-07T17:17:36.7872339+01:00  [ERR] The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_Countries_Continents_ContinentId". The conflict occurred in database "GeoServiceDB", table "dbo.Continents", column 'Id'.
The statement has been terminated. (44efe189)
2021-01-07T17:17:53.0253811+01:00  [INF] Application is shutting down... (90f52c38)
2021-01-07T17:21:23.0274846+01:00  [ERR] The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_Countries_Continents_ContinentId". The conflict occurred in database "GeoServiceDB", table "dbo.Continents", column 'Id'.
The statement has been terminated. (44efe189)
2021-01-07T17:21:38.1825063+01:00  [INF] Application is shutting down... (90f52c38)
2021-01-07T17:28:21.1300281+01:00  [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at GeoService.API.Controllers.ContinentController.PutContinent(Int32 id, ContinentInApi continentIn) in C:\Users\Chania\Documents\Programmeren\Jaar2\Web 4\GeoServiceGitHub\GeoService\GeoService.API\Controllers\ContinentController.cs:line 88
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-01-07T17:29:01.1894902+01:00  [INF] Application is shutting down... (90f52c38)
2021-01-07T17:33:29.8806263+01:00  [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at GeoService.API.Controllers.ContinentController.PutContinent(Int32 id, ContinentInApi continentIn) in C:\Users\Chania\Documents\Programmeren\Jaar2\Web 4\GeoServiceGitHub\GeoService\GeoService.API\Controllers\ContinentController.cs:line 88
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-01-07T17:33:44.6694421+01:00  [INF] Application is shutting down... (90f52c38)
2021-01-07T19:20:14.1113095+01:00  [ERR] The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_Countries_Continents_ContinentId". The conflict occurred in database "GeoServiceDB", table "dbo.Continents", column 'Id'.
The statement has been terminated. (44efe189)
2021-01-07T19:21:12.9616422+01:00 0HM5J73FH2PQ3:00000002 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at GeoService.API.Controllers.ContinentController.PutContinent(Int32 id, ContinentInApi continentIn) in C:\Users\Chania\Documents\Programmeren\Jaar2\Web 4\GeoServiceGitHub\GeoService\GeoService.API\Controllers\ContinentController.cs:line 88
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-01-07T19:21:12.9631212+01:00 0HM5J73FH2PQ3:00000002 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at GeoService.API.Controllers.ContinentController.PutContinent(Int32 id, ContinentInApi continentIn) in C:\Users\Chania\Documents\Programmeren\Jaar2\Web 4\GeoServiceGitHub\GeoService\GeoService.API\Controllers\ContinentController.cs:line 88
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-01-07T19:21:50.8295474+01:00  [ERR] The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_Countries_Continents_ContinentId". The conflict occurred in database "GeoServiceDB", table "dbo.Continents", column 'Id'.
The statement has been terminated. (44efe189)
2021-01-07T19:27:19.4919617+01:00  [ERR] The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_Countries_Continents_ContinentId". The conflict occurred in database "GeoServiceDB", table "dbo.Continents", column 'Id'.
The statement has been terminated. (44efe189)
2021-01-07T19:27:45.3188613+01:00  [INF] Application is shutting down... (90f52c38)
2021-01-07T19:28:15.9404915+01:00  [ERR] The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_Countries_Continents_ContinentId". The conflict occurred in database "GeoServiceDB", table "dbo.Continents", column 'Id'.
The statement has been terminated. (44efe189)
2021-01-07T19:30:02.7228515+01:00 0HM5J77VBB5J2:00000002 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at GeoService.API.Controllers.ContinentController.PutContinent(Int32 id, ContinentInApi continentIn) in C:\Users\Chania\Documents\Programmeren\Jaar2\Web 4\GeoServiceGitHub\GeoService\GeoService.API\Controllers\ContinentController.cs:line 88
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-01-07T19:30:02.7244245+01:00 0HM5J77VBB5J2:00000002 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at GeoService.API.Controllers.ContinentController.PutContinent(Int32 id, ContinentInApi continentIn) in C:\Users\Chania\Documents\Programmeren\Jaar2\Web 4\GeoServiceGitHub\GeoService\GeoService.API\Controllers\ContinentController.cs:line 88
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-01-07T19:35:00.4371766+01:00  [ERR] The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_Countries_Continents_ContinentId". The conflict occurred in database "GeoServiceDB", table "dbo.Continents", column 'Id'.
The statement has been terminated. (44efe189)
2021-01-07T19:41:14.5700449+01:00  [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at GeoService.API.Controllers.ContinentController.PutContinent(Int32 id, ContinentInApi continentIn) in C:\Users\Chania\Documents\Programmeren\Jaar2\Web 4\GeoServiceGitHub\GeoService\GeoService.API\Controllers\ContinentController.cs:line 88
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-01-07T19:47:06.6565279+01:00  [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at GeoService.API.Controllers.ContinentController.PutContinent(Int32 id, ContinentInApi continentIn) in C:\Users\Chania\Documents\Programmeren\Jaar2\Web 4\GeoServiceGitHub\GeoService\GeoService.API\Controllers\ContinentController.cs:line 88
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-01-07T19:47:25.7803149+01:00  [INF] Application is shutting down... (90f52c38)
2021-01-07T19:48:52.9346126+01:00  [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at GeoService.API.Controllers.ContinentController.DeleteContinent(Int32 id) in C:\Users\Chania\Documents\Programmeren\Jaar2\Web 4\GeoServiceGitHub\GeoService\GeoService.API\Controllers\ContinentController.cs:line 133
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-01-07T19:49:11.7162373+01:00  [INF] Application is shutting down... (90f52c38)
2021-01-07T19:52:41.4766153+01:00  [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at GeoService.API.Controllers.ContinentController.DeleteContinent(Int32 id) in C:\Users\Chania\Documents\Programmeren\Jaar2\Web 4\GeoServiceGitHub\GeoService\GeoService.API\Controllers\ContinentController.cs:line 133
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-01-07T19:54:09.5228403+01:00  [ERR] Remove Continent - Continent still has countries. (b569aef6)
2021-01-07T20:18:51.4810367+01:00 0HM5J83Q78EB0:00000002 [INF] Get api/continent/97/country/15 called (47bd9a6e)
2021-01-07T20:18:51.4744863+01:00 0HM5J83Q78EB0:00000002 [INF] Get api/continent/97/country/15 called (47bd9a6e)
2021-01-07T20:19:16.8173003+01:00 0HM5J83Q78EB0:00000002 [ERR] Object reference not set to an instance of an object. (f59a5554)
2021-01-07T20:19:16.8172233+01:00 0HM5J83Q78EB0:00000002 [ERR] Object reference not set to an instance of an object. (f59a5554)
2021-01-07T20:24:16.2197305+01:00  [INF] Get api/continent/97/country/15 called (47bd9a6e)
2021-01-07T20:27:15.1479645+01:00  [INF] Get api/continent/97/country/15 called (47bd9a6e)
2021-01-07T20:27:37.4612621+01:00  [ERR] Object reference not set to an instance of an object. (f59a5554)
2021-01-07T20:28:15.4645716+01:00 0HM5J88UIMI24:00000002 [INF] Get api/continent/97/country/15 called (47bd9a6e)
2021-01-07T20:28:15.4663018+01:00 0HM5J88UIMI24:00000002 [INF] Get api/continent/97/country/15 called (47bd9a6e)
2021-01-07T20:29:58.3448585+01:00  [INF] Get api/continent/97/country/15 called (47bd9a6e)
2021-01-07T20:29:59.5161615+01:00  [ERR] FindCountry - country doesn't exist (d48a4c65)
2021-01-07T20:30:37.2832260+01:00  [INF] Get api/continent/97/country/15 called (47bd9a6e)
2021-01-07T20:32:36.5746974+01:00  [INF] Get api/continent/97/country/15 called (47bd9a6e)
2021-01-07T20:33:46.5250976+01:00  [INF] Get api/continent/97/country/15 called (47bd9a6e)
2021-01-07T20:36:58.9374985+01:00  [INF] Get api/continent/97/country/15 called (47bd9a6e)
2021-01-07T20:37:00.0886423+01:00  [ERR] Country with 15 is not found (90f80214)
2021-01-07T20:49:51.7542267+01:00  [INF] Post api/continent/97/country/14 called (2a8872bf)
2021-01-07T20:49:52.9461192+01:00  [ERR] Country - SetContinent - invalid continent (7a33000f)
2021-01-07T20:50:05.9141791+01:00 0HM5J8LIR8SRO:00000002 [INF] Post api/continent/97/country/14 called (2a8872bf)
2021-01-07T20:50:05.9159878+01:00 0HM5J8LIR8SRO:00000002 [INF] Post api/continent/97/country/14 called (2a8872bf)
2021-01-07T20:50:22.4644608+01:00 0HM5J8LIR8SRO:00000003 [INF] Get api/continent/84/country/14 called (1227dbe5)
2021-01-07T20:50:22.4646446+01:00 0HM5J8LIR8SRO:00000003 [INF] Get api/continent/84/country/14 called (1227dbe5)
2021-01-07T20:50:22.4646637+01:00 0HM5J8LIR8SRO:00000003 [INF] Get api/continent/84/country/14 called (1227dbe5)
2021-01-07T20:50:22.4684466+01:00 0HM5J8LIR8SRO:00000003 [ERR] Country with id14 is not found (24cad26a)
2021-01-07T20:50:22.4684950+01:00 0HM5J8LIR8SRO:00000003 [ERR] Country with id14 is not found (24cad26a)
2021-01-07T20:50:22.4684810+01:00 0HM5J8LIR8SRO:00000003 [ERR] Country with id14 is not found (24cad26a)
2021-01-07T20:54:29.9650215+01:00  [INF] Post api/continent/84/country/14 called (86cbd417)
2021-01-07T20:54:31.1461469+01:00  [ERR] Add Country - Country with name: Hggr9g already exist. (2774fafa)
2021-01-07T20:54:41.1160873+01:00 0HM5J8O5OA257:00000002 [INF] Post api/continent/84/country/14 called (86cbd417)
2021-01-07T20:54:41.1178885+01:00 0HM5J8O5OA257:00000002 [INF] Post api/continent/84/country/14 called (86cbd417)
2021-01-07T20:54:41.2713221+01:00 0HM5J8O5OA257:00000002 [ERR] An error occurred while updating the entries. See the inner exception for details. (5d65ae99)
2021-01-07T20:54:41.2713793+01:00 0HM5J8O5OA257:00000002 [ERR] An error occurred while updating the entries. See the inner exception for details. (5d65ae99)
2021-01-07T20:55:28.1721010+01:00  [INF] Post api/continent/84/country/14 called (86cbd417)
2021-01-07T20:55:36.6121722+01:00  [ERR] An error occurred while updating the entries. See the inner exception for details. (5d65ae99)
2021-01-07T20:56:29.6288159+01:00  [INF] Post api/continent/84/country/14 called (86cbd417)
2021-01-07T20:56:34.0275651+01:00  [ERR] The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_Countries_Continents_ContinentId". The conflict occurred in database "GeoServiceDB", table "dbo.Continents", column 'Id'.
The statement has been terminated. (44efe189)
2021-01-07T20:56:40.8621301+01:00  [INF] Application is shutting down... (90f52c38)
2021-01-07T20:57:21.0003031+01:00  [INF] Post api/continent/84/country/14 called (86cbd417)
2021-01-07T20:58:20.4574930+01:00  [ERR] The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_Countries_Continents_ContinentId". The conflict occurred in database "GeoServiceDB", table "dbo.Continents", column 'Id'.
The statement has been terminated. (44efe189)
2021-01-07T21:05:20.3762632+01:00  [INF] Post api/continent/84/country/14 called (86cbd417)
2021-01-07T21:07:23.5299980+01:00  [INF] Post api/continent/84/country/14 called (86cbd417)
2021-01-07T21:08:13.9455337+01:00 0HM5J8VABID5O:00000002 [INF] Get api/continent/84/country/14 called (1227dbe5)
2021-01-07T21:08:13.9472468+01:00 0HM5J8VABID5O:00000002 [INF] Get api/continent/84/country/14 called (1227dbe5)
2021-01-07T21:08:26.3260674+01:00 0HM5J8VABID5O:00000003 [INF] Get api/continent/84 called (b94943f6)
2021-01-07T21:08:26.3261936+01:00 0HM5J8VABID5O:00000003 [INF] Get api/continent/84 called (b94943f6)
2021-01-07T21:08:26.3262344+01:00 0HM5J8VABID5O:00000003 [INF] Get api/continent/84 called (b94943f6)
