2020-12-25T15:33:20.0820110+01:00  [INF] Post api/continent/ called (0def4a5a)
2020-12-25T15:50:29.3837387+01:00  [INF] Post api/continent/ called (0def4a5a)
2020-12-25T15:50:30.1069296+01:00  [ERR] Continent - Id invalid (6b53d4d9)
2020-12-25T15:51:02.4873631+01:00 0HM58SHLUOQDK:00000002 [INF] Post api/continent/ called (0def4a5a)
2020-12-25T15:51:02.4890396+01:00 0HM58SHLUOQDK:00000002 [INF] Post api/continent/ called (0def4a5a)
2020-12-25T15:51:57.7436388+01:00 0HM58SHLUOQDK:00000002 [ERR] Continent - Id invalid (6b53d4d9)
2020-12-25T15:51:57.7434503+01:00 0HM58SHLUOQDK:00000002 [ERR] Continent - Id invalid (6b53d4d9)
2020-12-25T15:52:48.0625324+01:00  [INF] Post api/continent/ called (0def4a5a)
2020-12-25T16:02:08.7441676+01:00  [INF] Post api/continent/ called (0def4a5a)
2020-12-25T16:12:33.4042637+01:00  [INF] Post api/continent/ called (0def4a5a)
2020-12-25T16:12:34.5929752+01:00  [ERR] The instance of entity type 'CountryDB' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values. (54543542)
2020-12-25T16:12:57.0356494+01:00 0HM58SU0HGAN4:00000002 [INF] Post api/continent/ called (0def4a5a)
2020-12-25T16:12:57.0373155+01:00 0HM58SU0HGAN4:00000002 [INF] Post api/continent/ called (0def4a5a)
2020-12-25T16:14:47.5857202+01:00  [INF] Post api/continent/ called (0def4a5a)
2020-12-25T16:16:11.3545249+01:00  [ERR] The instance of entity type 'CountryDB' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values. (54543542)
2020-12-25T16:59:06.1778221+01:00  [INF] Post api/continent/ called (0def4a5a)
2020-12-25T16:59:24.4049371+01:00 0HM58TO0PS4TE:00000002 [INF] Get api/continent/9 called (2465d79f)
2020-12-25T16:59:24.4065494+01:00 0HM58TO0PS4TE:00000002 [INF] Get api/continent/9 called (2465d79f)
2020-12-25T17:04:33.7414158+01:00  [INF] Post api/continent/ called (0def4a5a)
2020-12-25T17:04:39.4873539+01:00  [ERR] Country - SetContinent - not new (9afd22e2)
2020-12-25T17:06:13.7766570+01:00  [INF] Post api/continent/ called (0def4a5a)
2020-12-25T17:06:37.7951001+01:00  [INF] Post api/continent/ called (0def4a5a)
2020-12-25T17:07:42.4893434+01:00  [ERR] Country - SetContinent - not new (9afd22e2)
2020-12-25T17:09:56.1126806+01:00  [INF] Application is shutting down... (90f52c38)
2020-12-25T17:11:34.7703558+01:00  [INF] Post api/continent/ called (0def4a5a)
2020-12-25T17:11:35.9398245+01:00  [ERR] The instance of entity type 'CountryDB' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values. (54543542)
2020-12-25T17:12:03.2869441+01:00 0HM58TUVUTVUO:00000002 [INF] Post api/continent/ called (0def4a5a)
2020-12-25T17:12:03.2886386+01:00 0HM58TUVUTVUO:00000002 [INF] Post api/continent/ called (0def4a5a)
2020-12-25T17:20:08.3966842+01:00  [INF] Post api/continent/ called (0def4a5a)
2020-12-25T17:20:09.5630549+01:00  [ERR] The instance of entity type 'CountryDB' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values. (54543542)
2020-12-25T17:26:07.0529680+01:00  [INF] Post api/continent/ called (0def4a5a)
2020-12-25T17:44:48.4408548+01:00  [INF] Post api/continent/ called (0def4a5a)
2020-12-25T17:44:48.4855983+01:00  [ERR] Country - population invalid (be4e75af)
2020-12-25T17:45:43.5313683+01:00 0HM58UHI3S3TC:00000002 [INF] Post api/continent/ called (0def4a5a)
2020-12-25T17:45:43.5330020+01:00 0HM58UHI3S3TC:00000002 [INF] Post api/continent/ called (0def4a5a)
2020-12-25T17:48:00.3282923+01:00  [INF] Post api/continent/ called (0def4a5a)
2020-12-25T17:48:48.8247641+01:00  [INF] Post api/continent/ called (0def4a5a)
2020-12-25T17:52:40.2549663+01:00  [INF] Post api/continent/ called (0def4a5a)
2020-12-25T17:53:47.4134871+01:00  [INF] Post api/continent/ called (0def4a5a)
2020-12-25T17:56:09.1950268+01:00  [INF] Post api/continent/ called (0def4a5a)
2020-12-25T17:56:31.3673294+01:00  [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: No route matches the supplied values.
   at Microsoft.AspNetCore.Mvc.CreatedAtActionResult.OnFormatting(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncCore(ActionContext context, ObjectResult result, Type objectType, Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsync(ActionContext context, ObjectResult result)
   at Microsoft.AspNetCore.Mvc.ObjectResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-12-25T17:59:13.7019111+01:00  [INF] Post api/continent/ called (0def4a5a)
2020-12-25T18:02:13.6299953+01:00  [INF] Post api/continent/ called (0def4a5a)
2020-12-25T18:02:24.2961997+01:00  [ERR] Object reference not set to an instance of an object. (f59a5554)
